### ISSUE TITLE
Ice in schematic won't place water once broken

### ISSUE THREAD

**Issue by D4RKTARGET** [QuickCarpet/QuickCarpet#101]
**Versions**
- Minecraft: 1.17.1
- QuickCarpet: None

**Describe the bug**
When I loaded a schematic and tried to place ice in the schematic to break it and form a water stream, the ice block would break and no water would come out of the ice block

**To Reproduce**
1. Load Schematic
2. Place Ice Block
3. Break Ice Block
4. 

**Expected behavior**
No water will come from the ice block once broken in a loaded schematic

**Screenshots**

**Additional context**

**Comment by skyrising** [comment]
This is unrelated to QuickCarpet. You probably have an air block below the ice?
If not you might want to open the bug report for [Litematica](https://github.com/maruohon/litematica/issues) if that's what you're using.
