### ISSUE TITLE
Server crashed after a "/player" command

### ISSUE THREAD

**Issue by EmilRiedeman** [QuickCarpet/QuickCarpet#106]
**Versions**
- Minecraft: 1.17.1
- QuickCarpet: 3.1.1

**Crash report**
[crash-2021-08-14_22.22.32-server.txt](https://github.com/QuickCarpet/QuickCarpet/files/6987147/crash-2021-08-14_22.22.32-server.txt)

Was not able to spawn a player using "/player spawn Alex" (no confirmation output and no error in the console), and the server crashed after "/player [name] drop" (the targeted player was online). Both client and server have the latest quick carpet version. These commands also don't work in single player. The server has the Lithium mod (v0.7.3) too.

**Comment by skyrising** [comment]
3.1.1 does not work with 1.17.1, use 3.2.0-dev: https://github.com/QuickCarpet/QuickCarpet/actions/runs/1121892220
