### ISSUE TITLE
Update 1.15 Branch

### ISSUE THREAD

**Issue by the-just-luke** [QuickCarpet/QuickCarpet#113]
The 1.15 version is lacking a lot of major features present in more updated branches such as rules regarding spectator mode, fake players, and bots.

**Comment by JackTGG** [comment]
Most of the code can be easily backported. But idk if it's gonna happen form sky cause either he adds something or he's doing something else.

**Comment by skyrising** [comment]
I'm sorry, I only support the latest stable Minecraft version and try to keep up with snapshots. I don't have time to backport stuff, but the code is there so someone else can do it if they want to.
