### ISSUE TITLE
Incompatible Mod Set

### ISSUE THREAD

**Issue by Stephen7890** [QuickCarpet/QuickCarpet#127]
**Versions**

    Minecraft: Fabric Loader 0.12.12 1.18.1 on mac os 11.6
    QuickCarpet: 3.3.0+1.18

**Crash report**

net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'QuickCarpet' (quickcarpet) 3.3.0+1.18 (C:\Users\steph\AppData\Roaming\.minecraft\mods\quickcarpet-3.3.0+1.18.jar) with any version that is compatible with:
		 - carpet 1.4.57
Unmet dependency listing:
	 - Mod 'QuickCarpet' (quickcarpet) 3.3.0+1.18 is incompatible with any version of mod 'Carpet Mod' (carpet), but a matching version is present: 1.4.57!
		 - Mod 'Carpet Mod' (carpet) 1.4.57 is being loaded from C:\Users\steph\AppData\Roaming\.minecraft\mods\fabric-carpet-1.18.1-1.4.57+v220119.jar
Inactive mods:
	 - mod 'QuickCarpet' (quickcarpet) 3.3.0+1.18, reason: to replace
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: inactive parent mod (nested jar)
	 - mod 'QuickCarpet API' (quickcarpet-api) 1.1.0, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'QuickCarpet' (quickcarpet) 3.3.0+1.18 (C:\Users\steph\AppData\Roaming\.minecraft\mods\quickcarpet-3.3.0+1.18.jar) with any version that is compatible with:
		 - carpet 1.4.57
Unmet dependency listing:
	 - Mod 'QuickCarpet' (quickcarpet) 3.3.0+1.18 is incompatible with any version of mod 'Carpet Mod' (carpet), but a matching version is present: 1.4.57!
		 - Mod 'Carpet Mod' (carpet) 1.4.57 is being loaded from C:\Users\steph\AppData\Roaming\.minecraft\mods\fabric-carpet-1.18.1-1.4.57+v220119.jar
Inactive mods:
	 - mod 'QuickCarpet' (quickcarpet) 3.3.0+1.18, reason: to replace
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: inactive parent mod (nested jar)
	 - mod 'QuickCarpet API' (quickcarpet-api) 1.1.0, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

I have quickcarpet api, but even if i add it it still crashes. Also, the skyblock 3.2.1 says it needs a compatible set with carpet 1.4.57

**Comment by JacktheDevel0per** [comment]
You have carpet mod or mods using requiring or including carpet, quickcarpet is a replacement/fork of carpet, and they are not suppose to be used together.

**Comment by Stephen7890** [comment]
> You have carpet mod or mods using requiring or including carpet, quickcarpet is a replacement/fork of carpet, and they are not suppose to be used together.

Thx for helping me, also if you dont mind the mod skyblock 3.2.1 does not also work for world types. I'm trying to get a skyblock map with structures and biomes

**Comment by JacktheDevel0per** [comment]
Ohh hmm, that would be a better question for skyrising

**Comment by JacktheDevel0per** [comment]
But there might be a quickcarpet version of the skyblock mod

**Comment by Stephen7890** [comment]
> But there might be a quickcarpet version of the skyblock mod

ive tried finding one in github & curseforge but its not the same like pressing a button to have all biomes and structures for skyblock. I just really like to use ilmango's skyblock mod which i tried to fix, but failed.
