### ISSUE TITLE
Blacklist/Whitelist

### ISSUE THREAD

**Issue by 4lve** [QuickCarpet/QuickCarpet#136]
With the dispenser you can put the dispenserPlaceBlocks mode on all,none,blacklist,whitelist
But i can't find any way to modify either the blacklist or the whitelist. Is there already a inbuilt command for this?

**Comment by skyrising** [comment]
The lists can be through the block tags `carpet:dispenser_placeable_blacklist` and `carpet:dispenser_placeable_whitelist` by using a data pack. You can find the default definitions for them [here](https://github.com/QuickCarpet/QuickCarpet/tree/main/src/main/resources/data/carpet/tags/blocks)
