### ISSUE TITLE
Please let the auto crafting table can store recipe

### ISSUE THREAD

**Issue by TanChenyu** [QuickCarpet/QuickCarpet#143]
I'm always frustrated when I found the auto crafting table cannot craft complex recipe automatic (like anvil). I hope the crafting table can store a recipe and take item from hopper according to it.

**Comment by jakslxpwrm** [comment]
As I understand, it is not meant to do so. It is possible (but not easy) to autocraft complex recipes. Ilmango did explain that in this video https://www.youtube.com/watch?v=2_HL309IZ0M

**Comment by TanChenyu** [comment]
> As I understand, it is not meant to do so. It is possible (but not easy) to autocraft complex recipes. Ilmango did explain that in this video https://www.youtube.com/watch?v=2_HL309IZ0M (I am not skyrising, this is my personal opinion)

Well, maybe you're right. I found some video about how to deal with complex recipes.
