### ISSUE TITLE
StructureChannel: No updates sent with Lithium

### ISSUE THREAD

**Issue by skyrising** [QuickCarpet/QuickCarpet#145]
With Lithium the structure channel doesn't send any updates after the initial `register` because Lithium doesn't call `sendWatchPackets`

Workaround:
```properties
mixin.world.player_chunk_tick=false
```
in lithium.properties

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json
