### ISSUE TITLE
wrong versions

### ISSUE THREAD

**Issue by lucastristanf** [QuickCarpet/QuickCarpet#149]
the 3.5.0 version isn't made for minecraft 1.19.2 even though it says it in the github.
the correct version is 3.6.0 but it doesn't show it in the discord.

**Comment by lucastristanf** [comment]
so please just update the 1.19.2 dev version as a master zo modrith has it and than I will be able to use it with aternos and it will be easier for other people to see it.

**Comment by skyrising** [comment]
I made a GitHub release for 3.6.0-dev.25 now and also uploaded it to Modrinth
