### ISSUE TITLE
[BUG] Moving crafting grids with pistons lose their items in a spectacular fashon upon reloading a world

### ISSUE THREAD

**Issue by Hectoris919** [QuickCarpet/QuickCarpet#66]
Version: QuickCarpet v2.4.0 for 1.16.2 & 1.16.3
------------------------------------------------

As stated in the title, crafting grids lose their items when moved by pistons after joining a world (I had autoCraftingTable on).

When moved, the items that were inside the crafting table explode out of the crafting table.

However, this bug seems to sometimes fix itself when you pause and unpause the game

**Comment by skyrising** [comment]
Did you set the autoCraftingTable to default to true? I could imagine some issues with moving the crafting table block entity when autoCraftingTable and movableBlockEntities are both false.

**Comment by Hectoris919** [comment]
> Did you set the autoCraftingTable to default to true? I could imagine some issues with moving the crafting table block entity when autoCraftingTable and movableBlockEntities are both false.

I had autoCraftingTable on but movableTileEntities off - maybe there should be a change to autoCraftingTable in that makes it turn on movableTileEntities but only for crafting tables if movableTileEntities is turned off by the user. I had movableTileEntities off because I didn’t want any of my furnaces to move around in my autocrafting station (there are a lot of slime blocks involved)

**Comment by skyrising** [comment]
If I understand the description correctly this matches the intended behavior.
