### ISSUE TITLE
AutoCraftingTable causing game crash

### ISSUE THREAD

**Issue by Raevyn117** [QuickCarpet/QuickCarpet#96]
When either a player or a block with in inventory (eg hopper, dropper, dispenser, etc) adds or removes an item from the crafting table while AutoCraftingTable is set to "true" (and/or when "true" has been made the default setting), the game client will crash, throwing the following error: "An unexpected issue occurred and the game has crashed. We are sorry for the inconvenience. Exit Code: 0". I have also encountered other error messages during my testing, but have been unable to reproduce them (I'm not sure what I did to get them).

Edit: This happens in java 1.17.1. I had no trouble in 1.17.

**Comment by skyrising** [comment]
Which version of QuickCarpet are you using? Can you send the crash report? (found in .minecraft/crash-reports/)

**Comment by MRtecno98** [comment]
I'm having the exact same problem, here is a link to the crash report: https://paste.ee/p/l0Ema

**Comment by skyrising** [comment]
Are you using the 1.17 version of QuickCarpet (3.1.1) or the 1.17.1 version (3.2.0-dev)?

**Comment by MRtecno98** [comment]
Oh I'm using 3.1.1, didn't know there was a separate version for 1.17.1. My bad then I guess

**Comment by skyrising** [comment]
I'm gonna assume it's the same for @Raevyn117

**Comment by Raevyn117** [comment]
Sorry, I lost track of this thread after I decided to stop using the mod for a while. I'm sure this is also the case with me, but the latest release I see here is 3.1.1. How do I get 3.2.0? I don't see it anywhere that I can actually download. I even checked CurseForge, but nothing.
